/**
 * Generate SQL for 25 videos per engine. Run: node scripts/videos/generate-25-seed.js
 */
const fs = require('fs');
const path = require('path');

const DATA = [
  { slug: 'predator-79', topics: [
    ['Predator 79cc Unboxing', 'Unboxing the Predator 79cc.', 'unboxing'],
    ['Predator 79cc – What\'s in the Box', 'What comes in the Predator 79cc box.', 'unboxing'],
    ['Predator 79cc Mini Bike Mounting', 'Mounting the Predator 79cc on a mini bike.', 'installation'],
    ['Predator 79cc Installation – 3/4" Shaft and Mounting', 'Predator 79cc 3/4" shaft and mounting.', 'installation'],
    ['Predator 79cc Clutch and Chain Setup', 'Clutch and chain setup for Predator 79cc.', 'installation'],
    ['Predator 79cc Oil Change and Capacity', 'Oil change and capacity for Predator 79cc.', 'maintenance'],
    ['Predator 79cc Air Filter Service', 'Air filter service for Predator 79cc.', 'maintenance'],
    ['Predator 79cc Valve Lash Adjustment', 'Valve lash adjustment on Predator 79cc.', 'maintenance'],
    ['Predator 79cc Performance Mods and Upgrades', 'Performance mods for Predator 79cc.', 'modification'],
    ['Predator 79cc Governor Removal', 'Governor removal on Predator 79cc.', 'modification'],
    ['Predator 79cc Exhaust and Intake Upgrades', 'Exhaust and intake upgrades for Predator 79cc.', 'modification'],
    ['Predator 79cc Carburetor Jetting', 'Carburetor jetting for Predator 79cc.', 'modification'],
    ['Predator 79cc Won\'t Start – Troubleshooting', 'Troubleshooting no-start on Predator 79cc.', 'troubleshooting'],
    ['Predator 79cc Running Rich or Lean – Fixes', 'Fixing rich or lean running on Predator 79cc.', 'troubleshooting'],
    ['Predator 79cc Common Problems and Solutions', 'Common Predator 79cc problems and fixes.', 'troubleshooting'],
    ['Predator 79cc Break-In Procedure', 'Break-in procedure for Predator 79cc.', 'tutorial'],
    ['Predator 79cc First Run and Break-In', 'First run and break-in for Predator 79cc.', 'tutorial'],
    ['Predator 79cc Full Review', 'Full review of the Predator 79cc.', 'review'],
    ['Predator 79cc vs Honda GXH50 – Comparison', 'Predator 79cc vs Honda GXH50.', 'review'],
    ['Predator 79cc Long-Term Review', 'Long-term review of the Predator 79cc.', 'review'],
    ['Predator 79cc Tuning and Jetting Tips', 'Tuning and jetting tips for Predator 79cc.', 'tips'],
    ['Predator 79cc Best Mods for Mini Bikes', 'Best mods for Predator 79cc on mini bikes.', 'tips'],
    ['Predator 79cc Oil Type and Weight', 'Oil type and weight for Predator 79cc.', 'maintenance'],
    ['Predator 79cc Throttle and Choke Setup', 'Throttle and choke setup for Predator 79cc.', 'tutorial'],
    ['Predator 79cc Kill Switch and Wiring', 'Kill switch and wiring for Predator 79cc.', 'installation'],
  ]},
  { slug: 'predator-212-non-hemi', topics: [
    ['Predator 212 Non-Hemi Unboxing', 'Unboxing the Predator 212 Non-Hemi.', 'unboxing'],
    ['Predator 212 Non-Hemi – What\'s in the Box', 'What comes in the 212 Non-Hemi box.', 'unboxing'],
    ['Predator 212 Non-Hemi Go-Kart Mounting', 'Go-kart mounting for Predator 212 Non-Hemi.', 'installation'],
    ['Predator 212 Non-Hemi Installation – 3/4" Shaft', 'Predator 212 Non-Hemi 3/4" shaft install.', 'installation'],
    ['Predator 212 Non-Hemi Torque Converter Install', 'Torque converter install on 212 Non-Hemi.', 'installation'],
    ['Predator 212 Non-Hemi Oil Change and Maintenance', 'Oil change and maintenance for 212 Non-Hemi.', 'maintenance'],
    ['Predator 212 Non-Hemi Air Filter Service', 'Air filter service for 212 Non-Hemi.', 'maintenance'],
    ['Predator 212 Non-Hemi Valve Lash Adjustment', 'Valve lash on 212 Non-Hemi.', 'maintenance'],
    ['Predator 212 Non-Hemi Stage 1 Kit', 'Stage 1 kit on 212 Non-Hemi.', 'modification'],
    ['Predator 212 Non-Hemi Governor Removal', 'Governor removal on 212 Non-Hemi.', 'modification'],
    ['Predator 212 Non-Hemi Exhaust and Header', 'Exhaust and header for 212 Non-Hemi.', 'modification'],
    ['Predator 212 Non-Hemi Carburetor Jetting', 'Carburetor jetting for 212 Non-Hemi.', 'modification'],
    ['Predator 212 Non-Hemi Won\'t Start – Troubleshooting', 'No-start troubleshooting for 212 Non-Hemi.', 'troubleshooting'],
    ['Predator 212 Non-Hemi Running Rich or Lean', 'Rich or lean fixes for 212 Non-Hemi.', 'troubleshooting'],
    ['Predator 212 Non-Hemi Common Problems', 'Common 212 Non-Hemi problems.', 'troubleshooting'],
    ['Predator 212 Non-Hemi Break-In Procedure', 'Break-in for 212 Non-Hemi.', 'tutorial'],
    ['Predator 212 Non-Hemi First Run and Break-In', 'First run and break-in for 212 Non-Hemi.', 'tutorial'],
    ['Predator 212 Non-Hemi Full Review', 'Full review of 212 Non-Hemi.', 'review'],
    ['Predator 212 Non-Hemi vs Hemi – Comparison', '212 Non-Hemi vs Hemi comparison.', 'review'],
    ['Predator 212 Non-Hemi Long-Term Review', 'Long-term review of 212 Non-Hemi.', 'review'],
    ['Predator 212 Non-Hemi Tuning Tips', 'Tuning tips for 212 Non-Hemi.', 'tips'],
    ['Predator 212 Non-Hemi Best Mods for Go-Karts', 'Best go-kart mods for 212 Non-Hemi.', 'tips'],
    ['Predator 212 Non-Hemi Oil Type and Weight', 'Oil type and weight for 212 Non-Hemi.', 'maintenance'],
    ['Predator 212 Non-Hemi Throttle and Choke Setup', 'Throttle and choke for 212 Non-Hemi.', 'tutorial'],
    ['Predator 212 Non-Hemi Kill Switch and Wiring', 'Kill switch and wiring for 212 Non-Hemi.', 'installation'],
  ]},
  { slug: 'predator-212-hemi', topics: [
    ['Predator 212 Hemi Unboxing', 'Unboxing the Predator 212 Hemi.', 'unboxing'],
    ['Predator 212 Hemi – What\'s in the Box', 'What comes in the 212 Hemi box.', 'unboxing'],
    ['Predator 212 Hemi Go-Kart Mounting', 'Go-kart mounting for Predator 212 Hemi.', 'installation'],
    ['Predator 212 Hemi Installation – 3/4" Shaft', 'Predator 212 Hemi 3/4" shaft install.', 'installation'],
    ['Predator 212 Hemi Torque Converter Install', 'Torque converter install on 212 Hemi.', 'installation'],
    ['Predator 212 Hemi Oil Change and Maintenance', 'Oil change and maintenance for 212 Hemi.', 'maintenance'],
    ['Predator 212 Hemi Air Filter Service', 'Air filter service for 212 Hemi.', 'maintenance'],
    ['Predator 212 Hemi Valve Lash Adjustment', 'Valve lash on 212 Hemi.', 'maintenance'],
    ['Predator 212 Hemi Stage 1 Kit Install', 'Stage 1 kit on 212 Hemi.', 'modification'],
    ['Predator 212 Hemi Governor Removal', 'Governor removal on 212 Hemi.', 'modification'],
    ['Predator 212 Hemi Exhaust and Header Upgrade', 'Exhaust and header for 212 Hemi.', 'modification'],
    ['Predator 212 Hemi Carburetor Jetting', 'Carburetor jetting for 212 Hemi.', 'modification'],
    ['Predator 212 Hemi Won\'t Start – Troubleshooting', 'No-start troubleshooting for 212 Hemi.', 'troubleshooting'],
    ['Predator 212 Hemi Running Rich or Lean – Fixes', 'Rich or lean fixes for 212 Hemi.', 'troubleshooting'],
    ['Predator 212 Hemi Common Problems and Solutions', 'Common 212 Hemi problems.', 'troubleshooting'],
    ['Predator 212 Hemi Break-In Procedure', 'Break-in for 212 Hemi.', 'tutorial'],
    ['Predator 212 Hemi First Run and Break-In', 'First run and break-in for 212 Hemi.', 'tutorial'],
    ['Predator 212 Hemi Full Review', 'Full review of 212 Hemi.', 'review'],
    ['Predator 212 Hemi vs Ghost 212 – Comparison', '212 Hemi vs Ghost 212 comparison.', 'review'],
    ['Predator 212 Hemi Long-Term Review', 'Long-term review of 212 Hemi.', 'review'],
    ['Predator 212 Hemi Tuning and Jetting Tips', 'Tuning tips for 212 Hemi.', 'tips'],
    ['Predator 212 Hemi Best Mods for Go-Karts', 'Best go-kart mods for 212 Hemi.', 'tips'],
    ['Predator 212 Hemi Oil Type and Weight', 'Oil type and weight for 212 Hemi.', 'maintenance'],
    ['Predator 212 Hemi Throttle and Choke Setup', 'Throttle and choke for 212 Hemi.', 'tutorial'],
    ['Predator 212 Hemi Kill Switch and Wiring', 'Kill switch and wiring for 212 Hemi.', 'installation'],
  ]},
  { slug: 'predator-ghost', topics: [
    ['Predator Ghost 212 Unboxing', 'Unboxing the Predator Ghost 212.', 'unboxing'],
    ['Predator Ghost 212 – What\'s in the Box', 'What comes in the Ghost 212 box.', 'unboxing'],
    ['Predator Ghost 212 Go-Kart Mounting', 'Go-kart mounting for Ghost 212.', 'installation'],
    ['Predator Ghost 212 Installation – 3/4" Shaft', 'Ghost 212 3/4" shaft install.', 'installation'],
    ['Predator Ghost 212 Clutch and Drivetrain Setup', 'Clutch and drivetrain for Ghost 212.', 'installation'],
    ['Predator Ghost 212 Oil Change and Maintenance', 'Oil and maintenance for Ghost 212.', 'maintenance'],
    ['Predator Ghost 212 Air Filter Service', 'Air filter service for Ghost 212.', 'maintenance'],
    ['Predator Ghost 212 Valve Lash Adjustment', 'Valve lash on Ghost 212.', 'maintenance'],
    ['Predator Ghost 212 Stock vs Modded – Upgrades', 'Stock vs modded Ghost 212.', 'modification'],
    ['Predator Ghost 212 Governor and Performance Mods', 'Governor and performance mods for Ghost 212.', 'modification'],
    ['Predator Ghost 212 Exhaust and Header', 'Exhaust and header for Ghost 212.', 'modification'],
    ['Predator Ghost 212 Carburetor Jetting for Racing', 'Carb jetting for Ghost 212 racing.', 'modification'],
    ['Predator Ghost 212 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Ghost 212.', 'troubleshooting'],
    ['Predator Ghost 212 Running Rich or Lean', 'Rich or lean fixes for Ghost 212.', 'troubleshooting'],
    ['Predator Ghost 212 Common Problems', 'Common Ghost 212 problems.', 'troubleshooting'],
    ['Predator Ghost 212 Break-In Procedure', 'Break-in for Ghost 212.', 'tutorial'],
    ['Predator Ghost 212 First Run and Break-In', 'First run and break-in for Ghost 212.', 'tutorial'],
    ['Predator Ghost 212 Full Review', 'Full review of Ghost 212.', 'review'],
    ['Predator Ghost 212 vs 212 Hemi – Comparison', 'Ghost 212 vs 212 Hemi comparison.', 'review'],
    ['Predator Ghost 212 Long-Term Racing Review', 'Long-term racing review of Ghost 212.', 'review'],
    ['Predator Ghost 212 Tuning and Jetting Tips', 'Tuning tips for Ghost 212.', 'tips'],
    ['Predator Ghost 212 Best Mods for Racing', 'Best racing mods for Ghost 212.', 'tips'],
    ['Predator Ghost 212 Oil Type and Weight', 'Oil type and weight for Ghost 212.', 'maintenance'],
    ['Predator Ghost 212 Throttle and Choke Setup', 'Throttle and choke for Ghost 212.', 'tutorial'],
    ['Predator Ghost 212 Kill Switch and Wiring', 'Kill switch and wiring for Ghost 212.', 'installation'],
  ]},
  { slug: 'predator-224', topics: [
    ['Predator 224 Unboxing', 'Unboxing the Predator 224.', 'unboxing'],
    ['Predator 224 – What\'s in the Box', 'What comes in the Predator 224 box.', 'unboxing'],
    ['Predator 224 Go-Kart Mounting', 'Go-kart mounting for Predator 224.', 'installation'],
    ['Predator 224 Installation – 7/8" Shaft', 'Predator 224 7/8" shaft install.', 'installation'],
    ['Predator 224 Torque Converter Install', 'Torque converter install on Predator 224.', 'installation'],
    ['Predator 224 Oil Change and Maintenance', 'Oil and maintenance for Predator 224.', 'maintenance'],
    ['Predator 224 Air Filter Service', 'Air filter service for Predator 224.', 'maintenance'],
    ['Predator 224 Valve Lash Adjustment', 'Valve lash on Predator 224.', 'maintenance'],
    ['Predator 224 Stage 1 and Performance Mods', 'Stage 1 and performance mods for Predator 224.', 'modification'],
    ['Predator 224 Governor Removal', 'Governor removal on Predator 224.', 'modification'],
    ['Predator 224 Exhaust and Header', 'Exhaust and header for Predator 224.', 'modification'],
    ['Predator 224 Carburetor Jetting', 'Carburetor jetting for Predator 224.', 'modification'],
    ['Predator 224 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Predator 224.', 'troubleshooting'],
    ['Predator 224 Running Rich or Lean', 'Rich or lean fixes for Predator 224.', 'troubleshooting'],
    ['Predator 224 Common Problems', 'Common Predator 224 problems.', 'troubleshooting'],
    ['Predator 224 Break-In Procedure', 'Break-in for Predator 224.', 'tutorial'],
    ['Predator 224 First Run and Break-In', 'First run and break-in for Predator 224.', 'tutorial'],
    ['Predator 224 Full Review', 'Full review of Predator 224.', 'review'],
    ['Predator 224 vs 212 – Comparison', 'Predator 224 vs 212 comparison.', 'review'],
    ['Predator 224 Long-Term Review for Mud and Trail', 'Long-term review of Predator 224 for mud and trail.', 'review'],
    ['Predator 224 Tuning Tips', 'Tuning tips for Predator 224.', 'tips'],
    ['Predator 224 Best Mods for Torque', 'Best mods for torque on Predator 224.', 'tips'],
    ['Predator 224 Oil Type and Weight', 'Oil type and weight for Predator 224.', 'maintenance'],
    ['Predator 224 Throttle and Choke Setup', 'Throttle and choke for Predator 224.', 'tutorial'],
    ['Predator 224 Kill Switch and Wiring', 'Kill switch and wiring for Predator 224.', 'installation'],
  ]},
  { slug: 'predator-301', topics: [
    ['Predator 301 Unboxing', 'Unboxing the Predator 301.', 'unboxing'],
    ['Predator 301 – What\'s in the Box', 'What comes in the Predator 301 box.', 'unboxing'],
    ['Predator 301 Go-Kart Mounting', 'Go-kart mounting for Predator 301.', 'installation'],
    ['Predator 301 Installation – 1" Shaft', 'Predator 301 1" shaft install.', 'installation'],
    ['Predator 301 Torque Converter Install', 'Torque converter install on Predator 301.', 'installation'],
    ['Predator 301 Oil Change and Maintenance', 'Oil and maintenance for Predator 301.', 'maintenance'],
    ['Predator 301 Air Filter Service', 'Air filter service for Predator 301.', 'maintenance'],
    ['Predator 301 Valve Lash Adjustment', 'Valve lash on Predator 301.', 'maintenance'],
    ['Predator 301 Performance Mods', 'Performance mods for Predator 301.', 'modification'],
    ['Predator 301 Governor Removal', 'Governor removal on Predator 301.', 'modification'],
    ['Predator 301 Exhaust and Header', 'Exhaust and header for Predator 301.', 'modification'],
    ['Predator 301 Carburetor and Governor Mods', 'Carburetor and governor mods for Predator 301.', 'modification'],
    ['Predator 301 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Predator 301.', 'troubleshooting'],
    ['Predator 301 Running Rich or Lean', 'Rich or lean fixes for Predator 301.', 'troubleshooting'],
    ['Predator 301 Common Problems', 'Common Predator 301 problems.', 'troubleshooting'],
    ['Predator 301 Break-In Procedure', 'Break-in for Predator 301.', 'tutorial'],
    ['Predator 301 First Run and Break-In', 'First run and break-in for Predator 301.', 'tutorial'],
    ['Predator 301 Full Review', 'Full review of Predator 301.', 'review'],
    ['Predator 301 vs 420 – Comparison', 'Predator 301 vs 420 comparison.', 'review'],
    ['Predator 301 Long-Term Review', 'Long-term review of Predator 301.', 'review'],
    ['Predator 301 Tuning and 1" Shaft Tips', 'Tuning and 1" shaft tips for Predator 301.', 'tips'],
    ['Predator 301 Best Mods for Go-Karts', 'Best go-kart mods for Predator 301.', 'tips'],
    ['Predator 301 Oil Type and Weight', 'Oil type and weight for Predator 301.', 'maintenance'],
    ['Predator 301 Throttle and Choke Setup', 'Throttle and choke for Predator 301.', 'tutorial'],
    ['Predator 301 Kill Switch and Wiring', 'Kill switch and wiring for Predator 301.', 'installation'],
  ]},
  { slug: 'predator-420', topics: [
    ['Predator 420 Unboxing', 'Unboxing the Predator 420.', 'unboxing'],
    ['Predator 420 – What\'s in the Box', 'What comes in the Predator 420 box.', 'unboxing'],
    ['Predator 420 Go-Kart Mounting', 'Go-kart mounting for Predator 420.', 'installation'],
    ['Predator 420 Installation – 1" Shaft', 'Predator 420 1" shaft install.', 'installation'],
    ['Predator 420 Torque Converter Install', 'Torque converter install on Predator 420.', 'installation'],
    ['Predator 420 Oil Change and Maintenance', 'Oil and maintenance for Predator 420.', 'maintenance'],
    ['Predator 420 Air Filter Service', 'Air filter service for Predator 420.', 'maintenance'],
    ['Predator 420 Valve Lash Adjustment', 'Valve lash on Predator 420.', 'maintenance'],
    ['Predator 420 Stage 1 and Performance Mods', 'Stage 1 and performance mods for Predator 420.', 'modification'],
    ['Predator 420 Governor Removal', 'Governor removal on Predator 420.', 'modification'],
    ['Predator 420 Exhaust and Header', 'Exhaust and header for Predator 420.', 'modification'],
    ['Predator 420 Carburetor and Governor Mods', 'Carburetor and governor mods for Predator 420.', 'modification'],
    ['Predator 420 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Predator 420.', 'troubleshooting'],
    ['Predator 420 Running Rich or Lean', 'Rich or lean fixes for Predator 420.', 'troubleshooting'],
    ['Predator 420 Common Problems', 'Common Predator 420 problems.', 'troubleshooting'],
    ['Predator 420 Break-In Procedure', 'Break-in for Predator 420.', 'tutorial'],
    ['Predator 420 First Run and Break-In', 'First run and break-in for Predator 420.', 'tutorial'],
    ['Predator 420 Full Review', 'Full review of Predator 420.', 'review'],
    ['Predator 420 vs Honda GX390 – Comparison', 'Predator 420 vs Honda GX390 comparison.', 'review'],
    ['Predator 420 Long-Term Review', 'Long-term review of Predator 420.', 'review'],
    ['Predator 420 Tuning Tips', 'Tuning tips for Predator 420.', 'tips'],
    ['Predator 420 Best Mods for Go-Karts', 'Best go-kart mods for Predator 420.', 'tips'],
    ['Predator 420 Oil Type and Weight', 'Oil type and weight for Predator 420.', 'maintenance'],
    ['Predator 420 Throttle and Choke Setup', 'Throttle and choke for Predator 420.', 'tutorial'],
    ['Predator 420 Kill Switch and Wiring', 'Kill switch and wiring for Predator 420.', 'installation'],
  ]},
  { slug: 'predator-670', topics: [
    ['Predator 670 V-Twin Unboxing', 'Unboxing the Predator 670 V-Twin.', 'unboxing'],
    ['Predator 670 – What\'s in the Box', 'What comes in the Predator 670 box.', 'unboxing'],
    ['Predator 670 Go-Kart or Buggy Mounting', 'Mounting Predator 670 on go-kart or buggy.', 'installation'],
    ['Predator 670 Installation – 1" Shaft', 'Predator 670 1" shaft install.', 'installation'],
    ['Predator 670 Torque Converter and Drivetrain', 'Torque converter and drivetrain for Predator 670.', 'installation'],
    ['Predator 670 Oil Change and Maintenance', 'Oil and maintenance for Predator 670.', 'maintenance'],
    ['Predator 670 Air Filter and Dual Carb Service', 'Air filter and dual carb service for Predator 670.', 'maintenance'],
    ['Predator 670 Valve Lash Adjustment', 'Valve lash on Predator 670.', 'maintenance'],
    ['Predator 670 Performance Mods', 'Performance mods for Predator 670.', 'modification'],
    ['Predator 670 Governor and Carb Mods', 'Governor and carb mods for Predator 670.', 'modification'],
    ['Predator 670 Exhaust and Headers', 'Exhaust and headers for Predator 670.', 'modification'],
    ['Predator 670 Carburetor Jetting and Sync', 'Carburetor jetting and sync for Predator 670.', 'modification'],
    ['Predator 670 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Predator 670.', 'troubleshooting'],
    ['Predator 670 Electric Start Issues', 'Electric start issues on Predator 670.', 'troubleshooting'],
    ['Predator 670 Common Problems', 'Common Predator 670 problems.', 'troubleshooting'],
    ['Predator 670 Break-In Procedure', 'Break-in for Predator 670.', 'tutorial'],
    ['Predator 670 First Run and Break-In', 'First run and break-in for Predator 670.', 'tutorial'],
    ['Predator 670 V-Twin Full Review', 'Full review of Predator 670 V-Twin.', 'review'],
    ['Predator 670 vs Honda V-Twin – Comparison', 'Predator 670 vs Honda V-Twin comparison.', 'review'],
    ['Predator 670 Long-Term Review for Buggies', 'Long-term review of Predator 670 for buggies.', 'review'],
    ['Predator 670 Tuning and Wiring Tips', 'Tuning and wiring tips for Predator 670.', 'tips'],
    ['Predator 670 Best Mods for Buggies and UTVs', 'Best mods for Predator 670 on buggies and UTVs.', 'tips'],
    ['Predator 670 Oil Type and Weight', 'Oil type and weight for Predator 670.', 'maintenance'],
    ['Predator 670 Throttle and Choke Setup', 'Throttle and choke for Predator 670.', 'tutorial'],
    ['Predator 670 Charging System and Wiring', 'Charging system and wiring for Predator 670.', 'installation'],
  ]},
  { slug: 'honda-gx200', topics: [
    ['Honda GX200 Unboxing', 'Unboxing the Honda GX200.', 'unboxing'],
    ['Honda GX200 – What\'s in the Box', 'What comes in the Honda GX200 box.', 'unboxing'],
    ['Honda GX200 Go-Kart Mounting', 'Go-kart mounting for Honda GX200.', 'installation'],
    ['Honda GX200 Installation – 3/4" Shaft', 'Honda GX200 3/4" shaft install.', 'installation'],
    ['Honda GX200 Torque Converter Install', 'Torque converter install on Honda GX200.', 'installation'],
    ['Honda GX200 Oil Change and Maintenance', 'Oil and maintenance for Honda GX200.', 'maintenance'],
    ['Honda GX200 Air Filter Service', 'Air filter service for Honda GX200.', 'maintenance'],
    ['Honda GX200 Valve Lash Adjustment', 'Valve lash on Honda GX200.', 'maintenance'],
    ['Honda GX200 Performance Mods', 'Performance mods for Honda GX200.', 'modification'],
    ['Honda GX200 Governor Removal', 'Governor removal on Honda GX200.', 'modification'],
    ['Honda GX200 Exhaust and Header', 'Exhaust and header for Honda GX200.', 'modification'],
    ['Honda GX200 Carburetor Jetting', 'Carburetor jetting for Honda GX200.', 'modification'],
    ['Honda GX200 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Honda GX200.', 'troubleshooting'],
    ['Honda GX200 Running Rich or Lean', 'Rich or lean fixes for Honda GX200.', 'troubleshooting'],
    ['Honda GX200 Common Problems', 'Common Honda GX200 problems.', 'troubleshooting'],
    ['Honda GX200 Break-In Procedure', 'Break-in for Honda GX200.', 'tutorial'],
    ['Honda GX200 First Run and Break-In', 'First run and break-in for Honda GX200.', 'tutorial'],
    ['Honda GX200 Full Review', 'Full review of Honda GX200.', 'review'],
    ['Honda GX200 vs Predator 212 – Comparison', 'Honda GX200 vs Predator 212 comparison.', 'review'],
    ['Honda GX200 Long-Term Reliability Review', 'Long-term reliability review of Honda GX200.', 'review'],
    ['Honda GX200 Tuning Tips', 'Tuning tips for Honda GX200.', 'tips'],
    ['Honda GX200 Best Mods for Go-Karts', 'Best go-kart mods for Honda GX200.', 'tips'],
    ['Honda GX200 Oil Type and Weight', 'Oil type and weight for Honda GX200.', 'maintenance'],
    ['Honda GX200 Throttle and Choke Setup', 'Throttle and choke for Honda GX200.', 'tutorial'],
    ['Honda GX200 Kill Switch and Wiring', 'Kill switch and wiring for Honda GX200.', 'installation'],
  ]},
  { slug: 'briggs-206', topics: [
    ['Briggs 206 Unboxing', 'Unboxing the Briggs 206.', 'unboxing'],
    ['Briggs 206 LO206 – What\'s in the Box', 'What comes in the Briggs 206 LO206 box.', 'unboxing'],
    ['Briggs 206 Go-Kart Mounting', 'Go-kart mounting for Briggs 206.', 'installation'],
    ['Briggs 206 Installation – 3/4" Shaft', 'Briggs 206 3/4" shaft install.', 'installation'],
    ['Briggs 206 Clutch and Drivetrain Setup', 'Clutch and drivetrain for Briggs 206.', 'installation'],
    ['Briggs 206 Oil Change and Maintenance', 'Oil and maintenance for Briggs 206.', 'maintenance'],
    ['Briggs 206 Air Filter Service', 'Air filter service for Briggs 206.', 'maintenance'],
    ['Briggs 206 Pre-Race Maintenance', 'Pre-race maintenance for Briggs 206.', 'maintenance'],
    ['Briggs 206 LO206 Class Rules – No Mods', 'LO206 class rules – no mods allowed.', 'modification'],
    ['Briggs 206 Sealed Engine Explained', 'Briggs 206 sealed engine explained.', 'modification'],
    ['Briggs 206 Legal Upgrades and Parts', 'Legal upgrades and parts for Briggs 206.', 'modification'],
    ['Briggs 206 Carburetor – Stock Settings', 'Briggs 206 carburetor stock settings.', 'modification'],
    ['Briggs 206 Won\'t Start – Troubleshooting', 'No-start troubleshooting for Briggs 206.', 'troubleshooting'],
    ['Briggs 206 Running Issues – Fixes', 'Running issues and fixes for Briggs 206.', 'troubleshooting'],
    ['Briggs 206 Common Problems', 'Common Briggs 206 problems.', 'troubleshooting'],
    ['Briggs 206 Break-In Procedure', 'Break-in for Briggs 206.', 'tutorial'],
    ['Briggs 206 First Run and Break-In', 'First run and break-in for Briggs 206.', 'tutorial'],
    ['Briggs 206 LO206 Full Review', 'Full review of Briggs 206 LO206.', 'review'],
    ['Briggs 206 vs Clone 212 – Comparison', 'Briggs 206 vs clone 212 comparison.', 'review'],
    ['Briggs 206 Long-Term Racing Review', 'Long-term racing review of Briggs 206.', 'review'],
    ['Briggs 206 Tuning and Setup Tips', 'Tuning and setup tips for Briggs 206.', 'tips'],
    ['Briggs 206 Racing Tips and Best Practices', 'Racing tips and best practices for Briggs 206.', 'tips'],
    ['Briggs 206 Oil Type and Weight', 'Oil type and weight for Briggs 206.', 'maintenance'],
    ['Briggs 206 Throttle and Choke', 'Throttle and choke for Briggs 206.', 'tutorial'],
    ['Briggs 206 Kill Switch and Wiring', 'Kill switch and wiring for Briggs 206.', 'installation'],
  ]},
];

function esc(s) { return (s || '').replace(/'/g, "''"); }
function row(t, d, c, slug, fe, o) {
  return `('${esc(t)}', '${esc(d)}', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, '${c}', (SELECT id FROM engines WHERE slug = '${slug}'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', ${fe}, ${o}, true)`;
}

let sql = `-- ============================================================================
-- Seed 25 videos per engine (250 total). Engine-specific topics.
-- Replace PLACEHOLDER via Admin → Auto-fill URLs from YouTube or populate-from-youtube-api.ts
-- ============================================================================

DELETE FROM videos;

`;
for (const e of DATA) {
  sql += `-- ${e.slug} (25)\nINSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES\n`;
  sql += e.topics.map((t, i) => row(t[0], t[1], t[2], e.slug, i < 4, i)).join(',\n') + ';\n\n';
}

const out = path.join(__dirname, '..', '..', 'supabase', 'migrations', '20260116000019_seed_videos_25_per_engine.sql');
fs.writeFileSync(out, sql);
console.log('Wrote', out);
