-- ============================================================================
-- Add 10 more videos per engine (100 total). Does NOT delete existing videos.
-- Run after 20260116000019_seed_videos_25_per_engine.sql.
-- Replace PLACEHOLDER via Admin → Auto-fill URLs from YouTube or populate-from-youtube-api.ts
-- ============================================================================

-- predator-79 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 79cc Spark Plug and Ignition', 'Spark plug and ignition for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 79cc Fuel Line and Tank Setup', 'Fuel line and tank setup for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 79cc RPM and Rev Limit', 'RPM and rev limit for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 79cc Recoil Starter Repair', 'Recoil starter repair for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 79cc Pull Start Replacement', 'Pull start replacement for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 79cc Chassis and Mounting Plate', 'Chassis and mounting plate for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 79cc Mini Bike vs Go-Kart Setup', 'Mini bike vs go-kart setup for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 79cc Cold Start and Warm-Up', 'Cold start and warm-up for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 79cc Aftermarket Parts Overview', 'Aftermarket parts overview for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 79cc Noise and Exhaust Tips', 'Noise and exhaust tips for Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-212-non-hemi (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 212 Non-Hemi Spark Plug and Ignition', 'Spark plug and ignition for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 212 Non-Hemi Fuel Line and Tank', 'Fuel line and tank for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 212 Non-Hemi Stage 2 Upgrades', 'Stage 2 upgrades for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 212 Non-Hemi Recoil Starter Repair', 'Recoil starter repair for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 212 Non-Hemi Low Oil Shutdown', 'Low oil shutdown on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 212 Non-Hemi Chain Tension and Sprockets', 'Chain tension and sprockets for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 212 Non-Hemi Electric Start Conversion', 'Electric start conversion for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 212 Non-Hemi Dyno and Horsepower Test', 'Dyno and horsepower test for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 212 Non-Hemi Cold Start Tips', 'Cold start tips for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 212 Non-Hemi Budget Build Guide', 'Budget build guide for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-212-hemi (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 212 Hemi Spark Plug and Ignition', 'Spark plug and ignition for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 212 Hemi Fuel Line and Tank', 'Fuel line and tank for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 212 Hemi Stage 2 and Cam Upgrades', 'Stage 2 and cam upgrades for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 212 Hemi Recoil Starter Repair', 'Recoil starter repair for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 212 Hemi Low Oil Shutdown', 'Low oil shutdown on 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 212 Hemi Chain Tension and Sprockets', 'Chain tension and sprockets for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 212 Hemi Electric Start Conversion', 'Electric start conversion for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 212 Hemi Dyno and Horsepower Test', 'Dyno and horsepower test for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 212 Hemi Cold Start Tips', 'Cold start tips for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 212 Hemi Budget Build Guide', 'Budget build guide for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-ghost (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator Ghost 212 Spark Plug and Ignition', 'Spark plug and ignition for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator Ghost 212 Fuel Line and Tank', 'Fuel line and tank for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator Ghost 212 Cam and Rod Upgrades', 'Cam and rod upgrades for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator Ghost 212 Recoil Starter Repair', 'Recoil starter repair for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator Ghost 212 Low Oil Shutdown', 'Low oil shutdown on Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator Ghost 212 Chain and Sprocket Setup for Racing', 'Chain and sprocket setup for Ghost 212 racing.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator Ghost 212 Electric Start Conversion', 'Electric start conversion for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator Ghost 212 Dyno and Horsepower Test', 'Dyno and horsepower test for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator Ghost 212 Cold Start and Tuning', 'Cold start and tuning for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator Ghost 212 Budget Racing Build', 'Budget racing build for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-224 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 224 Spark Plug and Ignition', 'Spark plug and ignition for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 224 Fuel Line and Tank', 'Fuel line and tank for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 224 7/8" Shaft Adapters and Hubs', '7/8" shaft adapters and hubs for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 224 Recoil Starter Repair', 'Recoil starter repair for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 224 Low Oil Shutdown', 'Low oil shutdown on Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 224 Chain Tension and Sprockets', 'Chain tension and sprockets for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 224 Electric Start Conversion', 'Electric start conversion for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 224 Dyno and Torque Test', 'Dyno and torque test for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 224 Cold Start and Mud Use', 'Cold start and mud use for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 224 Budget Mud Kart Build', 'Budget mud kart build for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-301 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 301 Spark Plug and Ignition', 'Spark plug and ignition for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 301 Fuel Line and Tank', 'Fuel line and tank for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 301 1" Shaft Adapters and Hubs', '1" shaft adapters and hubs for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 301 Recoil Starter Repair', 'Recoil starter repair for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 301 Low Oil Shutdown', 'Low oil shutdown on Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 301 Chain Tension and Sprockets', 'Chain tension and sprockets for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 301 Electric Start and Charging', 'Electric start and charging for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 301 Dyno and Horsepower Test', 'Dyno and horsepower test for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 301 Cold Start Tips', 'Cold start tips for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 301 Budget Go-Kart Build', 'Budget go-kart build for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-420 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 420 Spark Plug and Ignition', 'Spark plug and ignition for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 420 Fuel Line and Tank', 'Fuel line and tank for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 420 1" Shaft Adapters and Hubs', '1" shaft adapters and hubs for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 420 Recoil Starter Repair', 'Recoil starter repair for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 420 Low Oil Shutdown', 'Low oil shutdown on Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 420 Chain Tension and Sprockets', 'Chain tension and sprockets for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 420 Electric Start and Charging', 'Electric start and charging for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 420 Dyno and Horsepower Test', 'Dyno and horsepower test for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 420 Cold Start Tips', 'Cold start tips for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 420 Budget Buggy Build', 'Budget buggy build for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- predator-670 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 670 Spark Plug and Ignition', 'Spark plug and ignition for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Predator 670 Fuel Line and Dual Tank Setup', 'Fuel line and dual tank setup for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Predator 670 Dual Carb Sync and Tuning', 'Dual carb sync and tuning for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Predator 670 Electric Start and Battery', 'Electric start and battery for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Predator 670 One Cylinder Firing', 'One cylinder not firing on Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Predator 670 Belt and Drive Setup', 'Belt and drive setup for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Predator 670 Performance Exhaust Build', 'Performance exhaust build for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Predator 670 Dyno and Horsepower Test', 'Dyno and horsepower test for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Predator 670 Cold Start and Choke', 'Cold start and choke for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Predator 670 UTV and Buggy Build Guide', 'UTV and buggy build guide for Predator 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- honda-gx200 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Honda GX200 Spark Plug and Ignition', 'Spark plug and ignition for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Honda GX200 Fuel Line and Tank', 'Fuel line and tank for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Honda GX200 Stage 2 and Cam', 'Stage 2 and cam for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Honda GX200 Recoil Starter Repair', 'Recoil starter repair for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Honda GX200 Low Oil Alert', 'Low oil alert on Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Honda GX200 Chain Tension and Sprockets', 'Chain tension and sprockets for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Honda GX200 Electric Start Conversion', 'Electric start conversion for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Honda GX200 Dyno and Reliability Test', 'Dyno and reliability test for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Honda GX200 Cold Start Tips', 'Cold start tips for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Honda GX200 Budget Go-Kart Build', 'Budget go-kart build for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

-- briggs-206 (+10, display_order 25-34)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Briggs 206 Spark Plug and Ignition', 'Spark plug and ignition for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 25, true),
('Briggs 206 Fuel Line and Tank', 'Fuel line and tank for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'installation', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 26, true),
('Briggs 206 Legal Air Filter Options', 'Legal air filter options for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'modification', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 27, true),
('Briggs 206 Recoil Starter Repair', 'Recoil starter repair for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 28, true),
('Briggs 206 Low Oil Shutdown', 'Low oil shutdown on Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 29, true),
('Briggs 206 Chain and Sprocket Setup for Racing', 'Chain and sprocket setup for Briggs 206 racing.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 30, true),
('Briggs 206 Carburetor Rebuild – Stock', 'Carburetor rebuild stock for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 31, true),
('Briggs 206 Dyno and Power Test', 'Dyno and power test for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'review', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 32, true),
('Briggs 206 Cold Start and Pre-Race', 'Cold start and pre-race for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 33, true),
('Briggs 206 Budget LO206 Kart Build', 'Budget LO206 kart build for Briggs 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 34, true);

