-- ============================================================================
-- Seed 15 videos per engine for all engines
-- Created: 2026-01-16
-- Replaces existing video seeds with 15 placeholder videos per engine.
-- Replace PLACEHOLDER in video_url with real YouTube IDs via Admin → Videos.
-- ============================================================================

DELETE FROM videos;

-- ============================================================================
-- Helper: 15 categories (2 unboxing, 2 installation, 2 maintenance, 2 modification,
-- 2 troubleshooting, 2 tutorial, 2 review, 1 tips). is_featured=true for first 3.
-- ============================================================================

-- Predator 79cc (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 79cc Unboxing and First Look', 'Unboxing the Predator 79cc. What comes in the box.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 79cc Installation on Mini Bike', 'How to mount and install the Predator 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'installation', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 79cc Oil Change and Maintenance', 'Oil change and basic maintenance.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 79cc Performance Mods', 'Simple performance mods for the 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'modification', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 79cc Won''t Start - Troubleshooting', 'Troubleshooting no-start on the 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 79cc Break-In and First Run', 'Break-in procedure for new 79cc engines.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 79cc Review for Mini Bikes', 'Review of the Predator 79cc for mini bikes and karts.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'review', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 79cc Tips and Best Practices', 'Tips for getting the most from your 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'tips', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 79cc Unboxing – What to Check', 'What to check when unboxing your 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 300, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 79cc Mounting and Wiring', 'Mounting and throttle wiring for 79cc.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'installation', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 79cc Air Filter and Carb Care', 'Air filter and carb maintenance.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 79cc Exhaust and Intake Upgrades', 'Exhaust and intake upgrade guide.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'modification', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 79cc Carburetor Adjustment', 'Carb adjustment for idle and performance.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 79cc Governor Removal How-To', 'Governor removal tutorial and considerations.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 79cc vs Honda GXH50 Comparison', 'Predator 79cc compared to Honda GXH50.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'predator-79'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 212 Non-Hemi (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 212 Non-Hemi Unboxing', 'Unboxing the Predator 212 Non-Hemi (flat-top).', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 212 Non-Hemi Go-Kart Install', 'Installing the 212 Non-Hemi in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 212 Non-Hemi Oil and Maintenance', 'Oil change and maintenance for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 212 Non-Hemi Stage 1 Kit', 'Stage 1 upgrade on the 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 900, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 212 Non-Hemi No-Start Fixes', 'Troubleshooting no-start on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 212 Non-Hemi Break-In', 'Break-in procedure for 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 212 Non-Hemi vs Hemi Review', '212 Non-Hemi vs Hemi – which to choose.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 212 Non-Hemi Reliability Tips', 'Tips for long life on the 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'tips', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 212 Non-Hemi First Look', 'First look at the 212 Non-Hemi out of the box.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 212 Non-Hemi Torque Converter', 'Torque converter install on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 840, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 212 Non-Hemi Valve Lash', 'Valve lash adjustment on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 212 Non-Hemi Cam and Rod', 'Cam and rod upgrade on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1020, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 212 Non-Hemi Carb Cleaning', 'Carburetor cleaning and jetting.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 212 Non-Hemi Governor Removal', 'Governor removal on 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 212 Non-Hemi Long-Term Review', 'Long-term review of the 212 Non-Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-non-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 212 Hemi (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 212 Hemi Unboxing', 'Unboxing the Predator 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 212 Hemi Go-Kart Installation', 'Installing the 212 Hemi in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 212 Hemi Oil and Maintenance', 'Oil change and maintenance for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 212 Hemi Stage 1 and 2 Build', 'Stage 1 and 2 performance build.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1200, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 212 Hemi Won''t Start – Fixes', 'Troubleshooting no-start on 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 212 Hemi Break-In Procedure', 'Break-in for new 212 Hemi engines.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 212 Hemi Review and Comparison', '212 Hemi review and vs other 212s.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 212 Hemi Tuning Tips', 'Tuning and jetting tips for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'tips', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 212 Hemi – What''s in the Box', 'What comes in the 212 Hemi box.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 212 Hemi Mounting and Throttle', 'Mounting and throttle setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'installation', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 212 Hemi Oil and Orientation', 'Oil level and engine orientation tips.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 212 Hemi Budget Build', 'Budget performance build for 212 Hemi.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 960, 'modification', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 212 Hemi Carburetor Issues', 'Carb adjustment and common issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 212 Hemi Governor Removal', 'Governor removal how-to.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 630, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 212 Hemi – Is It Worth It?', '212 Hemi value and performance review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'review', (SELECT id FROM engines WHERE slug = 'predator-212-hemi'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator Ghost 212 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator Ghost 212 Unboxing', 'Unboxing the Predator Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator Ghost 212 Go-Kart Install', 'Installing the Ghost 212 in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'installation', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator Ghost 212 Maintenance', 'Oil and maintenance for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator Ghost 212 Stock vs Modded', 'Stock vs modified Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 900, 'modification', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator Ghost 212 Troubleshooting', 'Common Ghost 212 issues and fixes.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator Ghost 212 Break-In', 'Break-in for the Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator Ghost 212 Racing Review', 'Ghost 212 for racing – full review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'review', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator Ghost 212 Racing Tips', 'Racing and setup tips for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'tips', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator Ghost 212 First Look', 'First look at the Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator Ghost 212 Clutch Setup', 'Clutch and drivetrain setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'installation', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator Ghost 212 Valve Check', 'Valve lash on Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator Ghost 212 Mods for Racing', 'Racing mods for Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 960, 'modification', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator Ghost 212 No-Start', 'Ghost 212 no-start troubleshooting.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator Ghost 212 Jetting Guide', 'Jetting the Ghost 212.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator Ghost 212 vs 212 Hemi', 'Ghost 212 vs 212 Hemi comparison.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'review', (SELECT id FROM engines WHERE slug = 'predator-ghost'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 224 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 224 Unboxing', 'Unboxing the Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 224 Installation – 7/8" Shaft', 'Installing the 224; 7/8" shaft and clutch.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'installation', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 224 Oil and Maintenance', 'Oil and maintenance for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 224 Performance Build', 'Performance build on the 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1080, 'modification', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 224 Troubleshooting', 'Common 224 issues and fixes.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 224 Break-In', 'Break-in for Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 224 vs 212 Review', '224 vs 212 – is the 224 worth it?', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 224 Torque Tips', 'Getting the most torque from the 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'tips', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 224 First Look', 'First look at the Predator 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 224 Torque Converter', 'Torque converter for 7/8" shaft.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 840, 'installation', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 224 Valve Adjustment', 'Valve lash on the 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 224 Big Bore and Cam', 'Big bore and cam on 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1140, 'modification', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 224 Carb and Governor', 'Carb and governor issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 224 Governor Removal', 'Governor removal on 224.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 224 Mud and Trail Review', '224 for mud and trail – review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'review', (SELECT id FROM engines WHERE slug = 'predator-224'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 301 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 301 Unboxing', 'Unboxing the Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 301 Go-Kart Installation', 'Installing the 301 in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 900, 'installation', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 301 Oil and Maintenance', 'Oil and maintenance for 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 301 Performance Mods', 'Performance mods for the 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1020, 'modification', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 301 Troubleshooting', '301 no-start and common issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 301 Break-In', 'Break-in for Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 301 Review', 'Full review of the Predator 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'review', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 301 1" Shaft Tips', '1" shaft and clutch tips.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'tips', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 301 – What''s in the Box', 'What comes with the 301.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 301 Mounting 1" Shaft', 'Mounting and 1" shaft setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'installation', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 301 Air Filter and Oil', 'Air filter and oil maintenance.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 301 Header and Exhaust', 'Header and exhaust upgrade.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'modification', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 301 Carb and Fuel', 'Carb and fuel system fixes.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 301 Governor and Jetting', 'Governor and jetting how-to.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 630, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 301 vs 420 Comparison', '301 vs 420 – which to choose.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'predator-301'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 420 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 420 Unboxing', 'Unboxing the Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 420 Go-Kart Installation', 'Installing the 420 in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 960, 'installation', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 420 Oil and Maintenance', 'Oil and maintenance for 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 420 Performance Build', 'Performance build on the 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1200, 'modification', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 420 Troubleshooting', '420 no-start and common issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 420 Break-In', 'Break-in for Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 420 Review', 'Full review of the Predator 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 840, 'review', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 420 Power and Torque Tips', 'Power and torque tips for 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tips', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 420 First Look', 'First look at the 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 390, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 420 Frame and Mounting', 'Frame mods and mounting the 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 900, 'installation', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 420 Valve Lash', 'Valve adjustment on 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 420 Cam and Header', 'Cam and header upgrade.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1080, 'modification', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 420 Carb and Governor', 'Carb and governor troubleshooting.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 630, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 420 Governor Removal', 'Governor removal on 420.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 420 vs Honda GX390', '420 vs Honda GX390 comparison.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'review', (SELECT id FROM engines WHERE slug = 'predator-420'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Predator 670 V-Twin (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Predator 670 V-Twin Unboxing', 'Unboxing the Predator 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Predator 670 Go-Kart Installation', 'Installing the 670 V-Twin in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1200, 'installation', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Predator 670 Oil and Maintenance', 'Oil and maintenance for 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Predator 670 Performance Mods', 'Performance mods for 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1320, 'modification', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Predator 670 Electric Start Issues', '670 electric start troubleshooting.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Predator 670 Break-In', 'Break-in for 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Predator 670 V-Twin Review', 'Full review of the 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 900, 'review', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Predator 670 Power and Wiring Tips', 'Power and wiring tips for 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'tips', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Predator 670 First Look', 'First look at the 670 V-Twin.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'unboxing', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Predator 670 Mounting and Shaft', 'Mounting and 1" shaft setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 960, 'installation', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Predator 670 Oil and Filter', 'Oil and filter change on 670.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'maintenance', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Predator 670 Exhaust and Intake', 'Exhaust and intake upgrade.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1140, 'modification', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Predator 670 Carb and Fuel', 'Carb and fuel system fixes.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 690, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Predator 670 Charging System', 'Charging and electric start setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'tutorial', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Predator 670 for Buggies and UTVs', '670 for buggies and UTVs – review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 840, 'review', (SELECT id FROM engines WHERE slug = 'predator-670'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Honda GX200 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Honda GX200 Unboxing', 'Unboxing the Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'unboxing', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Honda GX200 Go-Kart Installation', 'Installing the GX200 in a go-kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'installation', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Honda GX200 Oil and Maintenance', 'Oil and maintenance for GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Honda GX200 Performance Mods', 'Performance mods for GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 960, 'modification', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Honda GX200 Troubleshooting', 'GX200 no-start and common issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Honda GX200 Break-In', 'Break-in for Honda GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'tutorial', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Honda GX200 vs Clone Review', 'GX200 vs Predator and clone engines.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'review', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Honda GX200 Reliability Tips', 'Tips for GX200 longevity.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'tips', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Honda GX200 First Look', 'First look at the GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Honda GX200 Clutch and Drivetrain', 'Clutch and drivetrain setup.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'installation', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Honda GX200 Valve Adjustment', 'Valve lash on GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'maintenance', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Honda GX200 Racing Build', 'Racing build for GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 1080, 'modification', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Honda GX200 Carb Tuning', 'Carb tuning and jetting.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 570, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Honda GX200 Maintenance Schedule', 'Maintenance schedule for GX200.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'tutorial', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Honda GX200 Long-Term Review', 'Long-term GX200 review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'honda-gx200'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- Briggs & Stratton 206 (15)
INSERT INTO videos (title, description, video_url, thumbnail_url, duration_seconds, category, engine_id, channel_name, channel_url, published_date, is_featured, display_order, is_active) VALUES
('Briggs 206 Unboxing', 'Unboxing the Briggs & Stratton 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'unboxing', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 0, true),
('Briggs 206 LO206 Kart Installation', 'Installing the 206 in an LO206 kart.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 780, 'installation', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 1, true),
('Briggs 206 Oil and Maintenance', 'Oil and sealed-engine maintenance.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'maintenance', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', true, 2, true),
('Briggs 206 – No Mods Allowed', 'Why the 206 is sealed; no modifications.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'modification', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 3, true),
('Briggs 206 Troubleshooting', '206 no-start and common issues.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 4, true),
('Briggs 206 Break-In', 'Break-in for LO206 racing.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 480, 'tutorial', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 5, true),
('Briggs 206 LO206 Class Review', '206 for LO206 class – full review.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 720, 'review', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 6, true),
('Briggs 206 Racing Tips', 'Racing and setup tips for 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 450, 'tips', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 7, true),
('Briggs 206 First Look', 'First look at the 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 360, 'unboxing', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 8, true),
('Briggs 206 Mounting and Chain', 'Mounting and chain setup for 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 630, 'installation', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 9, true),
('Briggs 206 Seal and Tech', 'Seal and tech inspection for 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 420, 'maintenance', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 10, true),
('Briggs 206 Legal Parts', 'Legal parts and prep for LO206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 600, 'modification', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 11, true),
('Briggs 206 Carb Issues', 'Carb issues on sealed 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 540, 'troubleshooting', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 12, true),
('Briggs 206 Pre-Race Checklist', 'Pre-race checklist for 206.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 510, 'tutorial', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 13, true),
('Briggs 206 vs Predator 212', '206 vs Predator 212 for racing.', 'https://www.youtube.com/watch?v=PLACEHOLDER', NULL, 660, 'review', (SELECT id FROM engines WHERE slug = 'briggs-206'), 'GoKart Builds', 'https://www.youtube.com', '2024-01-01', false, 14, true);

-- ============================================================================
-- NOTE: All video_url use PLACEHOLDER. Replace with real YouTube IDs via
-- Admin → Videos, or bulk-import with scripts/videos/import-videos.ts
-- ============================================================================
